### ISSUE TITLE
LIbrary causes incorrect Temperature Readings for the Si7021 Temperature Sensor. 

### ISSUE THREAD

**Issue by stuckstr** [sparkfun/SparkFun_Photon_Weather_Shield_Library#4]
Line 116 and line 124 of the .cpp file uses a constant of 175.25. However; I t should use a constant of 175.72 per the Si7021 data sheet.  When this is corrected the Si7021 sensor will give correct temperature readings.

**Comment by cmfrancis** [comment]
This has been updated. See page 22 of the data sheet for information.
https://cdn.sparkfun.com/datasheets/Sensors/Weather/Si7021.pdf
